### ISSUE TITLE
PyInquirer...

### ISSUE THREAD

**Issue by phishpy** [BenChaliah/Arbitrium-RAT#17]
root@localhost:/usr/local/Arbitrium-RAT-main/ArbitriumCLI# python2.7 main.py
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from PyInquirer import prompt
  File "/usr/local/lib/python2.7/dist-packages/PyInquirer-1.0.3-py2.7.egg/PyInquirer/__init__.py", line 6, in <module>
    from prompt_toolkit.token import Token
  File "/usr/local/lib/python2.7/dist-packages/prompt_toolkit-1.0.14-py2.7.egg/prompt_toolkit/__init__.py", line 16, in <module>
    from .interface import CommandLineInterface
  File "/usr/local/lib/python2.7/dist-packages/prompt_toolkit-1.0.14-py2.7.egg/prompt_toolkit/interface.py", line 9, in <module>
    import six
ImportError: No module named six
root@localhost:/usr/local/Arbitrium-RAT-main/ArbitriumCLI#

**Comment by phishpy** [comment]
Please, is there anybody to assist?

**Comment by BenChaliah** [comment]
I'm not sure of the solution or the cause since the issue in question has to do with PyInquirer library and your environment. But this: `pip2 install six` and let me know

**Comment by phishpy** [comment]
Thank you Sir,



I will try as instructed and feed you back with the outcome.



If it work I will buy you a coffee. Good work. Keep it up.
